//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reparations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reparations()
        {
            this.LigneReparation = new HashSet<LigneReparation>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public decimal Cout { get; set; }
        public int VehiculeID { get; set; }
        public int EmployeID { get; set; }
    
        public virtual Employes Employes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LigneReparation> LigneReparation { get; set; }
        public virtual Vehicules Vehicules { get; set; }
    }
}
